# Identifying the Industry Collaborators of an Academic Institution

Dimensions has an enormous amount of data about organizations and you can query this data with the Dimensions Analytics API.

In this tutorial we identify all organizations that have an `industry` type. 

This list of organizations is then used to identify industry collaborations for a chosen academic institution.

In [1]:
import datetime
print("==\nCHANGELOG\nThis notebook was last run on %s\n==" % datetime.date.today().strftime('%b %d, %Y'))

==
CHANGELOG
This notebook was last run on Sep 10, 2025
==

## Prerequisites

This notebook assumes you have installed the [Dimcli](https://pypi.org/project/dimcli/) library and are familiar with the ['Getting Started' tutorial](https://api-lab.dimensions.ai/cookbooks/1-getting-started/1-Using-the-Dimcli-library-to-query-the-API.html).

In [2]:
!pip install dimcli plotly tqdm -U --quiet 

import dimcli
from dimcli.utils import *

import os, sys, time, json
from tqdm.notebook import tqdm as progress
import pandas as pd
import plotly.express as px
if not 'google.colab' in sys.modules:
  # make js dependecies local / needed by html exports
  from plotly.offline import init_notebook_mode
  init_notebook_mode(connected=True)
#

print("==\nLogging in..")
# https://digital-science.github.io/dimcli/getting-started.html#authentication
ENDPOINT = "https://app.dimensions.ai"
if 'google.colab' in sys.modules:
  import getpass
  KEY = getpass.getpass(prompt='API Key: ')  
  dimcli.login(key=KEY, endpoint=ENDPOINT)
else:
  KEY = ""
  dimcli.login(key=KEY, endpoint=ENDPOINT)
dsl = dimcli.Dsl()

Searching config file credentials for 'https://app.dimensions.ai' endpoint..

==
Logging in..
Dimcli - Dimensions API Client (v1.4)
Connected to: <https://app.dimensions.ai/api/dsl> - DSL v2.12
Method: dsl.ini file

## 1. Selecting an academic institution

For the purpose of this exercise, we will use University of Trento, Italy (organization ID `grid.11696.39`) as a starting point. 
You can pick any other organization of course. Just use a [DSL query](https://digital-science.github.io/dimensions-api-lab/cookbooks/8-organizations/1-GRID-preview.html) to discover the ID of an organization that interests you.

In [3]:
#@markdown The main organization we are interested in:
ORGID = "grid.11696.39" #@param {type:"string"}
    
#@markdown The start/end year of publications used to extract industry collaborations:
YEAR_START = 2000 #@param {type: "slider", min: 1950, max: 2020}
YEAR_END = 2016 #@param {type: "slider", min: 1950, max: 2020}

if YEAR_END < YEAR_START:
  YEAR_END = YEAR_START

#
# gen link to Dimensions
#
try:
  orgname = dsl.query(f"""search organizations where id="{ORGID}" return organizations[name]""", verbose=False).organizations[0]['name']
except:
  orgname = ""
from IPython.display import display, HTML
display(HTML('Organization: <a href="{}" title="View selected organization in Dimensions">{} - {} &#x29c9;</a>'.format(dimensions_url(ORGID), ORGID, orgname)))
display(HTML('Time period: {} to {} <br /><br />'.format(YEAR_START, YEAR_END)))

## 2. Extracting publications from industry collaborations

First of all we want to extract all GRID orgs with `type='Company'` using the API. Then we will use this list of organizations to identify industry collaborators for our chosen institution. 

* We can use the [dimcli.query_iterative](https://digital-science.github.io/dimensions-api-lab/cookbooks/1-getting-started/1-Using-the-Dimcli-library-to-query-the-API.html#Iterative-querying-(loops)) method to automatically retrieve 'company' GRID orgs in batches of 1000. 
* NOTE this step retrieves several thousands records from the API so it may take a few minutes to complete.

In [4]:
# get GRID IDs 
company_grids = dsl.query_iterative("""search organizations where types="Company" return organizations[id]""")

Starting iteration with limit=1000 skip=0 ...
0-1000 / 158994 (0.60s)
1000-2000 / 158994 (0.59s)
2000-3000 / 158994 (4.55s)
3000-4000 / 158994 (0.58s)
4000-5000 / 158994 (0.62s)
5000-6000 / 158994 (2.44s)
6000-7000 / 158994 (2.06s)
7000-8000 / 158994 (4.03s)
8000-9000 / 158994 (1.97s)
9000-10000 / 158994 (2.47s)
10000-11000 / 158994 (0.63s)
11000-12000 / 158994 (0.57s)
12000-13000 / 158994 (1.93s)
13000-14000 / 158994 (0.65s)
14000-15000 / 158994 (2.35s)
15000-16000 / 158994 (2.11s)
16000-17000 / 158994 (3.86s)
17000-18000 / 158994 (6.32s)
18000-19000 / 158994 (0.71s)
19000-20000 / 158994 (3.59s)
20000-21000 / 158994 (0.72s)
21000-22000 / 158994 (3.72s)
22000-23000 / 158994 (5.98s)
23000-24000 / 158994 (0.61s)
24000-25000 / 158994 (0.71s)
25000-26000 / 158994 (1.70s)
26000-27000 / 158994 (1.34s)
27000-28000 / 158994 (4.45s)
28000-29000 / 158994 (0.70s)
29000-30000 / 158994 (0.56s)
30000-31000 / 158994 (1.76s)
31000-32000 / 158994 (0.64s)
32000-33000 / 158994 (0.58s)
33000-34000 / 158994 (0.70s)
34000-35000 / 158994 (2.38s)
35000-36000 / 158994 (2.06s)
36000-37000 / 158994 (0.71s)
37000-38000 / 158994 (3.82s)
38000-39000 / 158994 (0.65s)
39000-40000 / 158994 (4.50s)
40000-41000 / 158994 (5.95s)
41000-42000 / 158994 (0.81s)
42000-43000 / 158994 (0.65s)
43000-44000 / 158994 (4.53s)
44000-45000 / 158994 (0.61s)
45000-46000 / 158994 (4.54s)
46000-47000 / 158994 (0.60s)
47000-48000 / 158994 (0.78s)
48000-49000 / 158994 (0.74s)
49000-50000 / 158994 (0.68s)
===
Records extracted: 50000

We can now set up a parametrized query that pulls Dimensions publications resulting from industry collaborations. 

Together with IDs, title and DOIs, the publications generated from industry collaborations should include citations counts and authors info, so that we can draw up some useful statistics based on these metadata later on.

In [5]:
query_template = """
    search publications
       where
        research_orgs.id = "{}"
        and research_orgs.id in {}
        and year in [{}:{}]
    return publications[id+doi+type+times_cited+year+authors]
    """

In [7]:
orgids = list(company_grids.as_dataframe()['id'])

#
# loop through all organizations

ITERATION_RECORDS = 1000  # Publication records per query iteration
ORG_RECORDS = 200       # organization IDs per query
VERBOSE = False          # set to True to view full extraction logs
print(f"===\nExtracting {ORGID} publications with industry collaborators ...")
print("Records per query : ", ITERATION_RECORDS)
print("Organization IDs per query: ", ORG_RECORDS)
results = []


for chunk in progress(list(chunks_of(orgids, ORG_RECORDS))):
    query = query_template.format(ORGID, json.dumps(chunk), YEAR_START, YEAR_END)
#     print(query)
    data = dsl.query_iterative(query, verbose=VERBOSE, limit=ITERATION_RECORDS)
    if data.errors:
        print("==\nIteration failed: due an error no data was extracted for this iteration. \nTry adjusting the ITERATION_RECORDS or BATCHSIZE parameters and rerun the extraction.")
    else:
        results += data.publications
    time.sleep(0.5)
    
#
# put the publication data into a dataframe, remove duplicates and save

pubs = pd.DataFrame().from_dict(results)
# print("===\nIndustry Publications found: ", len(pubs))
pubs.drop_duplicates(subset='id', inplace=True)
print("Unique Industry Publications found: ", len(pubs))

#
# preview the data
print("===\nPreview:")
pubs.head(10)

===
Extracting grid.11696.39 publications with industry collaborators ...
Records per query :  1000
Organization IDs per query:  200

  0%|          | 0/250 [00:00<?, ?it/s]

Unique Industry Publications found:  101
===
Preview:

,authors,doi,id,times_cited,type,year
0,"[{'affiliations': [{'city': 'Dublin', 'city_id...",10.1109/eucnc.2016.7561056,pub.1094950798,28,proceeding,2016
1,"[{'affiliations': [{'city': 'Dublin', 'city_id...",10.1109/noms.2016.7503003,pub.1094654631,35,proceeding,2016
2,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1002/adem.201400134,pub.1049335111,50,article,2014
3,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1111/j.1551-2916.2005.00043.x,pub.1042663343,64,article,2005
4,"[{'affiliations': [{'city': 'Legnaro', 'city_i...",10.1016/s0168-583x(03)01322-3,pub.1041242454,14,article,2003
5,"[{'affiliations': [{'city': 'MENLO PARK', 'cit...",10.1111/jace.12485,pub.1033867339,48,article,2013
6,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1145/2663204.2663254,pub.1033777395,225,proceeding,2014
7,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1140/epjds/s13688-016-0064-6,pub.1033140941,25,article,2016
8,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1145/2063518.2063544,pub.1028019246,1,proceeding,2011
9,"[{'affiliations': [{'city': 'Trento', 'city_id...",10.1089/big.2014.0054,pub.1018945654,68,article,2015

## 3. Analyses 

In this section we will build some visualizations that help understanding the data we extracted. 

### 3.1 Count of Publications per year from Industry Collaborations

A simple histogram chart can tell us the rate of publications per year.

In [9]:
px.histogram(pubs, 
             x="year", 
             color="type",
             title=f"Publications per year with industry collaborations for {ORGID}")

### 3.2 Citations from Industry Collaboration

In [10]:
pubs_grouped = pubs.groupby(['year'], as_index=False).sum()
px.bar(pubs_grouped, 
       x="year", 
       y="times_cited",
       title=f"Tot Citations per year for publications with industry collaborations for {ORGID}")

### 3.3 Top Industry Collaborators

In order to dig deeper into the industry affiliations we have to process the **nested JSON data** in the 'authors' column. By doing so, we can process authors & affiliations information and identify the ones belonging to the 'industry' set defined above.  

For example, if we extract the authors data for the first publication/row (`pubs.iloc[0]['authors']`), this is what it'd look like: 

```
[{'first_name': 'LUCA DALLA',
  'last_name': 'VALLE',
  'corresponding': '',
  'orcid': '',
  'current_organization_id': 'grid.11696.39',
  'researcher_id': 'ur.013645226073.38',
  'affiliations': [{'id': 'grid.11696.39',
    'name': 'University of Trento',
    'city': 'Trento',
    'city_id': 3165243,
    'country': 'Italy',
    'country_code': 'IT',
    'state': None,
    'state_code': None}]},
 {'first_name': 'ELENA CRISTINA',
  'last_name': 'RADA',
  'corresponding': '',
  'orcid': "['0000-0003-0807-1826']",
  'current_organization_id': 'grid.18147.3b',
  'researcher_id': 'ur.01344320306.26',
  'affiliations': [{'id': 'grid.11696.39',
    'name': 'University of Trento',
    'city': 'Trento',
    'city_id': 3165243,
    'country': 'Italy',
    'country_code': 'IT',
    'state': None,
    'state_code': None}]},
 {'first_name': 'MARCO',
  'last_name': 'RAGAZZI',
  'corresponding': '',
  'orcid': '',
  'current_organization_id': 'grid.11696.39',
  'researcher_id': 'ur.0655652202.53',
  'affiliations': [{'id': 'grid.11696.39',
    'name': 'University of Trento',
    'city': 'Trento',
    'city_id': 3165243,
    'country': 'Italy',
    'country_code': 'IT',
    'state': None,
    'state_code': None}]},
 {'first_name': 'MICHELE',
  'last_name': 'CARAVIELLO',
  'corresponding': '',
  'orcid': '',
  'current_organization_id': 'grid.14587.3f',
  'researcher_id': 'ur.016015622301.36',
  'affiliations': [{'id': 'grid.14587.3f',
    'name': 'Telecom Italia (Italy)',
    'city': 'Rome',
    'city_id': 3169070,
    'country': 'Italy',
    'country_code': 'IT',
    'state': None,
    'state_code': None}]}]
```

NOTE: Instead of iterating through the authors/affiliations data by building a new function, we can just take advantage of the `DslDataset` class in the [Dimcli](https://digital-science.github.io/dimensions-api-lab/cookbooks/1-getting-started/1-Using-the-Dimcli-library-to-query-the-API.html) library. This class abstracts the notion of a Dimensions 'results list' and provides useful methods to quickly process authors and affiliations.

In [13]:
from dimcli import DslDataset

# create a new DslDataset instance
pubsnew = DslDataset.from_publications_list(pubs)
# extract affiliations as a dataframe
affiliations = pubsnew.as_dataframe_authors_affiliations()
# focus only on affiliations including a grid from the industry set created above
affiliations = affiliations[affiliations['aff_id' ].isin(orgids)]
# preview the data
affiliations.head(5)

/opt/miniconda3/envs/apilab/lib/python3.12/site-packages/dimcli/core/dataframe_factory.py:195: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

,aff_city,aff_city_id,aff_country,aff_country_code,aff_id,aff_name,aff_raw_affiliation,aff_state,aff_state_code,pub_id,researcher_id,first_name,last_name
2,Paris,2988507.0,France,FR,grid.89485.38,Orange SA,"Orange S.A., France",,,pub.1094950798,ur.014561075723.99,Imen Grida Ben,Yahia
7,Madrid,3117735.0,Spain,ES,grid.99308.3b,Telefonica Investigacion y Desarrollo SA,"Telefonica I+D, Spain",,,pub.1094950798,ur.016452362717.24,Antonio,Pastor
8,Madrid,3117735.0,Spain,ES,grid.99308.3b,Telefonica Investigacion y Desarrollo SA,"Telefonica I+D, Spain",,,pub.1094950798,ur.014322160107.95,Pedro A.,Aranda
24,Madrid,3117735.0,Spain,ES,grid.99308.3b,Telefonica Investigacion y Desarrollo SA,Telefonica I+d,,,pub.1094654631,ur.014574231073.91,Diego R.,Lopez
34,Paris,2988507.0,France,FR,grid.89485.38,Orange SA,"Orange, France",,,pub.1094654631,ur.014561075723.99,Imen Grida Ben,Yahia

Let's now count frequency and create a nice chart summing up the top industry collaborators.

TIP Try zooming in on the left-hand side to put into focus the organizations that appear most frequently.

In [14]:
px.histogram(affiliations, 
             x="aff_name", 
             height=900,
             title=f"Top Industry collaborators for {ORGID}").update_xaxes(categoryorder="total descending")

### 3.4 Countries of Industry Collaborators

We can use the same dataset to segment the data by country.

In [15]:
px.pie(affiliations, 
       names="aff_country", 
       height=600, 
       title=f"Countries of collaborators for {ORGID}")

### 3.5 Putting Countries and Collaborators together

**TIP** by clicking on the right panel you can turn on/off specific countries

In [16]:
px.histogram(affiliations, 
             x="aff_name", 
             height=900, 
             color="aff_country",
             title=f"Top Countries and Industry collaborators for {orgname}-{ORGID}",
             color_discrete_sequence=px.colors.diverging.Spectral)